In [79]:
import numpy as np
from numpy import *;

x = np.array([[1,2,3],[4,5,6]])
beta = np.array([1,2,3])

y = np.array([beta[0]*x[:,0]+beta[1]*x[:,1]+beta[2]*x[:,1]*x[:,2]])
y = np.transpose(y)
print(y)

[[ 23]
 [104]]


In [94]:
x = np.array([1,2,3,4,5])
alpha = np.array([1,2,3])
beta = np.array([2,2,2])

n = len(x)
m = len(alpha)

yhat = np.zeros(n)
for i in range(n):
    for j in range(m):
        yhat[i] += alpha[j]*np.exp(-beta[j]*x[i])
        
print(yhat)

[8.12011699e-01 1.09893833e-01 1.48725131e-02 2.01277577e-03
 2.72399579e-04]


In [122]:
x = np.array([1,2,3,4,5])
beta = np.array([2,2,2])
alpha = np.array([1,2,3])

l = len(beta)
beta = np.array([beta]*x.shape[0])
beta = np.transpose(beta)
x = np.array([x]*l)
y = alpha.dot(np.exp(-beta*x))

print(y)

[8.12011699e-01 1.09893833e-01 1.48725131e-02 2.01277577e-03
 2.72399579e-04]


In [133]:
x = np.array([[1,2,3],[2,3,4],[5,6,7]])
y = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])

n , d= x.shape
m, d = y.shape
y = y[0:n]
mid = (x - y)**2
mid = np.transpose(mid)
one = np.array([1]*d)
mid = one.dot(mid)
dist = np.array([mid] * m)
dist = np.transpose(dist)
print(dist)
#print(dist)

[[ 5  5  5  5]
 [ 5  5  5  5]
 [29 29 29 29]]


In [134]:
dist = np.zeros((n,m))
for i in range(n):
    for j in range(m):
        for k in range(d):
            dist[i,j] += (x[i,k]-y[i,k])**2
print(dist)

[[ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [29. 29. 29. 29.]]
